### ISSUE TITLE
Potential bug in climacell_precip for sub-daily time steps 

### ISSUE THREAD

**Issue by hussainkazmi** [nikdata/RClimacell#1]
Thanks for the great library! 
While everything else seemed to work fine, the climacell_precip function seems to return incorrect data points when used with sampling intervals of less than 1d. For example, when I use the following code:

`climacell_precip(api_key = Sys.getenv("CLIMACELL_API"), lat = 41.878685, long = -87.636011, timestep = '1h', start_time = Sys.time(), end_time = Sys.time() + lubridate::days(3))`

I get the following result:

_

> # A tibble: 5 x 13
>   start_time          precipitation_i… precipitation_p… precipitation_t… precipitation_t…
>   <dttm>                         <dbl>            <dbl>            <dbl> <chr>           
> 1 2021-02-21 12:00:00              4.1               95                2 Snow            
> 2 2021-02-22 12:00:00              0                  0                1 Rain            
> 3 2021-02-23 12:00:00              0                  0                1 Rain            
> 4 2021-02-24 12:00:00              0                  0                2 Snow            
> 5 2021-02-25 12:00:00              0                  0                2 Snow

_            

Which looks quite similar to what you would get if you used a timestep of 1d. Can you please take a look?

Many thanks!

**Comment by nikdata** [comment]
Thanks @hussainkazmi for the issue. I think I found the bug. Really silly bug on my part. I'm still recovering from a medical procedure, but should be back on my feet soon. I will get this fixed in a few days' time - sorry about the delay.

**Comment by hussainkazmi** [comment]
No problem, and thank you for the quick response! Get well soon!

**Comment by nikdata** [comment]
@hussainkazmi can you try the dev version and see if the issue has been fixed?

``` r
devtools::install_github("nikdata/RClimacell")
```

**Comment by hussainkazmi** [comment]
I tried with the dev version, but it seems to still return only the daily values regardless of the sample. 

If I request sub-daily intervals, it returns daily sampled data, with the following warning 'Climacell Free API only allows for upto 6 hours into the future! Readjusting end time to no more than 6 hours from start time.' This indicates it is retrieving hourly data at some point. 

Perhaps, there is an issue with the variable that is actually being returned?

**Comment by nikdata** [comment]
@hussainkazmi thank you for your patience! I think I finally found the main culprit. In addition to the other bug, this one had to do with the parameterization of the dates. Basically, I wasn't using the user start/end dates (which are modified if they violate the ClimaCell API rules). Now that it's fixed, it should be working well!

Can you take another look by installing the dev version again, please?

**Comment by hussainkazmi** [comment]
Just tried and I think it is still not working unfortunately (sorry for being a pain!). Here is the output I got from the latest dev version (tried with both 15m and 1h time steps):

```r
Rows: 6
Columns: 13
$ start_time                <dttm> 2021-02-24 12:00:00, 2021-02-25 12:00:00, 2021-02-26 12:00:00,…
$ precipitation_intensity   <dbl> 0.0000, 0.0000, 0.0000, 0.1202, 0.1185, 0.0000
$ precipitation_probability <dbl> 0, 0, 15, 20, 10, 0
$ precipitation_type_code   <dbl> 1, 2, 1, 1, 2, 2
$ precipitation_type_desc   <chr> "Rain", "Snow", "Rain", "Rain", "Snow", "Snow"
$ visibility                <dbl> 13.01, 16.00, 16.00, 18.70, 24.14, 24.14
$ pressure_surface_level    <dbl> 993.78, 995.23, 986.95, 981.68, 988.26, 992.12
$ pressure_sea_level        <dbl> 1028.68, 1021.46, 1009.28, 1008.85, 1011.13, 1023.55
$ cloud_cover               <dbl> 58.69, 100.00, 98.44, 92.19, 86.95, 0.00
$ cloud_base                <dbl> 0.40, 0.65, 3.18, 7.59, 0.43, 0.00
$ cloud_ceiling             <dbl> 0.00, 0.58, 3.40, 8.94, 0.92, 0.00
$ weather_code              <dbl> 1101, 2100, 1102, 4000, 4000, 1000
$ weather_desc              <chr> "Partly Cloudy", "Light Fog", "Mostly Cloudy", "Drizzle", "Driz…
```

**Comment by nikdata** [comment]
@hussainkazmi Thanks for your patience! I've tried to reproduce the error you're seeing, but I can't. I've ran the updated code (dev side - not CRAN) and get expected results.

input:

```r
library(RClimacell)
climacell_precip(api_key = Sys.getenv("CLIMACELL_API"), 
                 lat = 41.878685, 
                 long = -87.636011, 
                 timestep = '15m', 
                 start_time = Sys.time(), 
                 end_time = Sys.time() + lubridate::days(3)
                 )
```

output:

```r

# A tibble: 24 x 13
   start_time          precipitation_int… precipitation_pro… precipitation_typ… precipitation_ty… visibility pressure_surface…
   <dttm>                           <dbl>              <dbl>              <dbl> <chr>                  <dbl>             <dbl>
 1 2021-02-25 17:25:00                  0                  0                  1 Rain                      10             1009.
 2 2021-02-25 17:40:00                  0                  0                  1 Rain                      12             1009.
 3 2021-02-25 17:55:00                  0                  0                  1 Rain                      15             1009.
 4 2021-02-25 18:10:00                  0                  0                  1 Rain                      16             1009.
 5 2021-02-25 18:25:00                  0                  0                  1 Rain                      16             1009.
 6 2021-02-25 18:40:00                  0                  0                  1 Rain                      16             1009.
 7 2021-02-25 18:55:00                  0                  0                  1 Rain                      16             1009.
 8 2021-02-25 19:10:00                  0                  0                  1 Rain                      16             1009.
 9 2021-02-25 19:25:00                  0                  0                  1 Rain                      16             1008.
10 2021-02-25 19:40:00                  0                  0                  1 Rain                      16             1008.
# … with 14 more rows, and 6 more variables: pressure_sea_level <dbl>, cloud_cover <dbl>, cloud_base <dbl>,
#   cloud_ceiling <dbl>, weather_code <dbl>, weather_desc <chr>
Warning message:
In climacell_precip(api_key = Sys.getenv("CLIMACELL_API"), lat = 41.878685,  :
  Climacell Free API only allows for upto 6 hours into the future!
Readjusting end time to no more than 6 hours from start time.
```

Can you share what version of RClimacell you are using? You should be on 0.1.1. If you're already on the latest dev version, perhaps you can send some screenshots of what you're seeing or the log outputs?

I've also edited your last post to use three back ticks (`) for marking code.

**Comment by nikdata** [comment]
@hussainkazmi again, thank you for your patience. I've made another update to the package. Seems like the API doesn't return values for certain fields. I've added a check to fix this. From the testing I've done, I'm seeing results that match expectations when using time steps less than 1 hour.

Can you try this new version (version 0.1.2). It should resolve the issues that you are seeing.

If you use macOS, I **highly** recommend updating the {lubridate} package to 1.7.10 (on CRAN).

**Comment by hussainkazmi** [comment]
@nikdata I just had the chance to try this again, and after updating all the libraries (including lubridate) it works perfectly now! 
Thanks again for your persistence in fixing this issue, much appreciated!
As an aside, data_precip$cloud_base and data_precip$cloud_ceiling seem to be returning all NaNs for now, maybe those are the fields you mention in your comment?

**Comment by nikdata** [comment]
@hussainkazmi great news!

As for the cloud_base and cloud_ceiling variables, they do have lots of NA values if the API does not return a value for a specific date/time combination. Climacell's API doesn't return all variable values I've noticed. In those instances, this package simply inserts an NA value instead of dropping the entire 'row'.
